ALTER TABLE cloak_policies
  ADD COLUMN use_ip_blacklist BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN use_header_rules BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN require_sec_fetch_mode BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN use_js_probe BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN use_asn BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN use_ptr BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN block_datacenter_asn BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN block_datacenter_ptr BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN block_verified_bot_ptr BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN ptr_timeout_ms INTEGER NOT NULL DEFAULT 800,
  ADD COLUMN ptr_cache_hours INTEGER NOT NULL DEFAULT 6;

ALTER TABLE route_cloak_configs
  ADD COLUMN use_ip_blacklist BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN use_header_rules BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN require_sec_fetch_mode BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN use_js_probe BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN use_asn BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN use_ptr BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN block_datacenter_asn BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN block_datacenter_ptr BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN block_verified_bot_ptr BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN ptr_timeout_ms INTEGER NOT NULL DEFAULT 800,
  ADD COLUMN ptr_cache_hours INTEGER NOT NULL DEFAULT 6;

CREATE TABLE ptr_cache (
  ip INET PRIMARY KEY,
  host TEXT NOT NULL DEFAULT '',
  is_datacenter BOOLEAN NOT NULL DEFAULT FALSE,
  is_verified_bot BOOLEAN NOT NULL DEFAULT FALSE,
  error_count INTEGER NOT NULL DEFAULT 0,
  checked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_ptr_cache_expires ON ptr_cache(expires_at);
